// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'ccf-info'
  | 'get-ccf-info'
  | 'paper-info-update'
  | 'requesting-ccf-rank-multiple'
  | 'requesting-ccf-rank-single';
